### ISSUE TITLE
EncounterRunner: Habilitar controles para hacer daño, curación o escudo a varios objetivos al mismo tiempo.

### ISSUE THREAD

**Issue by EliteRaptoR** [EliteRaptoR/DugeonMasterSquire#18]

**Comment by EliteRaptoR** [comment]
Esta funcional pero hay que probarlo en sesión. Ademas el checkbox esta ahí tirado hay que arreglarlo

**Comment by Rayffer** [comment]
He reorganizado un poco la UI, dime qué te parece

**Comment by Rayffer** [comment]
Cierro la issue porque ya está hecho, rediseñar la ui lo hacemos como otro issue
