### ISSUE TITLE
EncounterRunner: Botón para editar la iniciativa de la party.

### ISSUE THREAD

**Issue by EliteRaptoR** [EliteRaptoR/DugeonMasterSquire#19]
Estaría bien tener un botón que (por ejemplo con el form de la calc) te pidiera la iniciativa de la party jugador por jugador y que al acabar ordenase la tabla de party por iniciativa.

**Comment by Rayffer** [comment]
He integrado la función del registrador de iniciativas, un nuevo formulario tonto que he hecho, al boton "Set Initiative"
