### ISSUE TITLE
Añadir más de monstruos

### ISSUE THREAD

**Issue by EliteRaptoR** [EliteRaptoR/DugeonMasterSquire#3]
Añadir información del bestiario al csv. El csv no tiene estadísticas como STR DEX, etc y hemos encontrado un proyecto en github donde esta toda esa información. Podríamos crear un nuevo documento json con la información del csv y los archivos del bestiario.

**Comment by EliteRaptoR** [comment]
He puesto los ficheros en la carpeta post dentro de la solucion

**Comment by Rayffer** [comment]
Fusionados ambos archivos, cierro issue
