### ISSUE TITLE
Crear un formulario para editar la party y sus stats

### ISSUE THREAD

**Issue by EliteRaptoR** [EliteRaptoR/DugeonMasterSquire#33]

**Comment by Rayffer** [comment]
Creado un formulario para editar la party y los stats.

Tenemos que hablar como hacer la parte de añadir un nuevo miembro al grupo, yo usaría el mismo formulario para modificar los aspectos del personaje.

**Comment by EliteRaptoR** [comment]
Cierro el issue porque el form esta operativo. Si surgen más ideas para incorporar al form ya abriremos otro.
