### ISSUE TITLE
Terminar los iconos de daños y estados. 

### ISSUE THREAD

**Issue by EliteRaptoR** [EliteRaptoR/DugeonMasterSquire#36]
Esto esta casi pero es importante. Es un lio cuando tengo que poner un estado que no esta en la calculadora. Lo de los colores lo podemos revisar juntos antes de hacer los iconos. Otra opcion es que los colores se generen en la aplicación en vez de tener tantos archivos con tantos colores. Igual se podria hacer con los tamaños. No creo que sean necesario que esten los archivos con todos los tamaños en la aplicacion de pueden generar.

**Comment by Rayffer** [comment]
Los colores podrían generarse perfectamente en la aplicación, a partir de una base.
Lo de los tamaños, es algo provisional por así decirlo, he creado a mansalva porque apenas ocupan espacio y así más adelante, podemos hacer que por configuración, tire de unos u otros y solo cargue los que necesita.

**Comment by Rayffer** [comment]
Lo de los colores, ahora que lo pienso, quizá es un poco más complicado, de lo que estoy pensando, hay que abordarlo con una idea clara, no quiero hacerlo al tuntun

**Comment by Rayffer** [comment]
Vale, ya tengo los nuevos iconos, echales un ojo y veamos qué se puede hacer

**Comment by Rayffer** [comment]
He creado una herramienta para redimensionar imagenes y recolorearlas, creo que es un poco matar moscas a cañonazos, además de que debe haber un memory leak por ahí porque la aplicación ahora consume 60 MB de memoria.

Se puede definir un icono de las dimensiones que queramos, ya sea cuadrado o no, además de especificar un color de los usados por winforms como color de las inmunidades, resistencias y vulnerabilidades

Cierro el issue.
