### ISSUE TITLE
Runner: Añadir ventana para editar el id de los monsters

### ISSUE THREAD

**Issue by EliteRaptoR** [EliteRaptoR/DugeonMasterSquire#39]

**Comment by Rayffer** [comment]
He implementado un nuevo formulario que permite definir varias cosas, míratelo a ver si te gusta el comportamiento y uso del mismo y me dices, sí?

**Comment by Rayffer** [comment]
Cierro el issue, ya está implementado el comportamiento que aquí se especifica.
